raw_data_dir: "./data/01-raw"
preprocessing_data_dir: "./data/02-preprocessed"
processed_data_dir: "./data/03-processed"

storage:
  video_subdir: "videos"
  audio_subdir: "audio"
  keyframes_subdir: "keyframes"

backend:
  host: "0.0.0.0"
  port: 8000
  reload: false

database:
  url: "sqlite:///backend/backend.db"
