video:
  video_model: yolov8x.pt

audio:
  task: "automatic-speech-recognition"
  model: "openai/whisper-medium.en"

database:
  db_path: "./data/02-preprocessed/extraction.db"
  video_events: |
    CREATE TABLE IF NOT EXISTS video_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        file_name TEXT NOT NULL,
        object_name TEXT NOT NULL,
        frame INTEGER NOT NULL,
        timestamp REAL NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
    );
  audio_events: |
    CREATE TABLE IF NOT EXISTS audio_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        file_name TEXT NOT NULL,
        transcript TEXT NOT NULL,
        start REAL NOT NULL,
        end REAL NOT NULL,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
    );
